### PR TITLE
stubbed out, maybe ok?

### PR DESCRIPTION
**Pull request by jschoch**
This is really for discussion, not tested yet.

1.  should MPG_MODE and Booster be separate config items or should we assume the booster will always have MPG mode?
2.  i was struggling with the gpio isr which I understand scrapes all the ports so I just did a xsemaphore and task instead.  I dont' think it is a big performance issue but maybe it smells.
3.  I was thinking of using selectStream but the esp32 code is pretty different than the other code.

### CODE REVIEW

**Comment by terjeio** [comment]
1. Separate as the pins could be assigned to something else. 

2. It should be added to inputpin[] array with a new group - similar handling as KEYPAD_STROBE_PIN.

3. Not sure, will have to look into this again. MPG mode should be usable with other streaming protocols than serial over USB. There may also be the possibility that some would want to use the second stream as the standard stream - to avoid the ESP OS messages completely.

I will do a more in depth review later.

**Comment by terjeio** [comment]
In `uartConfig()` in `esp32-hal-uart2.c` i believe you have to set the pin modes for UART operation as this is not done by the OS as for the USB port. There is code for that but commented out.

3. selectStream cannot be used. This is what needs to be done:

Use the MSP432 [driver.c](https://github.com/terjeio/grblHAL/blob/master/drivers/MSP432/driver.c) as a reference design.

When MPG mode is available this must be published in the driver capability flags, set in `driver_init()`:

```
#if MPG_MODE_ENABLE
    hal.driver_cap.mpg_mode = On;
#endif
```

The second stream need only to handle input if the standard serial output stream is available on a pin, it is on the ESP32.
If available connect the MPG RX input to that, it leaves the serial2 TX pin free(?) for other use and simplifies code.

In `modeSelect()` function:

Add a static `io_stream_t` struct.

Check if grbl is in a state that allows change, force a status report and return if not.

On changing to MPG mode:

Disable RX interrups for standard input stream, enable for MPG stream.*

Copy the active stream pointers in `hal.stream` to the local `io_stream_t` struct.
Change `hal.stream.read`, `hal.stream.get_rx_buffer_available`, `hal.stream.cancel_read_buffer` and `hal.stream.reset_read_buffer` to point to serial2 functions.

On changing from MPG mode:

Enable RX interrups for standard input stream, disable for MPG stream.*

Copy the local `io_stream_t` struct back to `hal.stream`.

Then:

Reset (flush) the newly activated input stream to get rid of any unwanted data.

Update the sys global to inform the core about the mode change.

Force a status report to inform the MPG and any connected sender about the mode change.

Depending on interrupt capabilities of the mode change pin it may be necessary to change it from rising to falling edge detection.

---

In `driver_init()` function:

Set the mpg input pin as output and drive it low.

---

In `settings_changed()` function:

Enable mpg pin as input with pullup.
Call `modeEnable()` after a delay to ensure grbl is up and running.

---

In `modeEnable()` function:

Call `modeSelect(true)` if `sys.mpg_mode` is different from mpg pin state.

Depending on interrupt capabilities of the mode change pin it may be necessary to change it from rising to falling edge detection here.

---

In mpg pin interrupt handler:

In the MSP432 driver I call `modeChange()` after a short delay, I cannot remember why now...

The `modeChange()` function is there for the delay, it calls `modeSelect()` with the current pin state.
The delay call returns immediately, the supplied function will be called when the delay timer times out.

---

The MSP432 drivers allows the use of a I2C keypad which works even in MPG mode is off, it may be possible to do something similar over serial2 by polling the RX stream to an additional input buffer and call `hal.protocol_enqueue_gcode` on line termination.
A polling function can be hooked into the `hal.execute_realtime` call.

*I need to look into how to handle this for non-serial streams. We do not want any real-time commands from them in MPG mode.

**Comment by terjeio** [comment]
You need to add MPG input pin to the inputpin[] array or otherwise (IIRC) the whole GPIO input handling needs to be rewritten... I can add it for you if you prefer that.

**Comment by terjeio** [comment]
Try with these files, uses the inputpin array - no crashing during limited testing. I've added an id to the inputpin array for flexibility - similar as for the SAM3X8E driver. I try to keep naming consistent across drivers where possible. MPG_ENABLE_PIN must be assigned a GPIO in the map file you use.

I've left out the stream switching code, for you to play with - or do you want me to give a hand with that too?

[ESP32MPG.zip](https://github.com/terjeio/grblHAL/files/4145220/ESP32MPG.zip)

**Comment by terjeio** [comment]
flummoxed by what?

**Comment by jschoch** [comment]
i had my stuff in setup not init.

i'm not seeing the stream switch, hal.stream.write seems to only write to UART0... so I took a break.

Wondering why the core hal lib was used, seems very complex.  The api outlined here seems a bit more manable: https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/peripherals/uart.html



i'll take a look after the super bowl.

**Comment by terjeio** [comment]
Ok. I have looked into switching streams at MPG mode change, with focus on the network streams. A bit tricky as they may connect/disconnect while the MPG is active, this has to be handled seamlessly.
I think I have it nailed down now - more testing another day, past midnight here.

The UART code was stripped down by me - for faster real-time command handling and also to allow manual tool change (with jogging enabled) and soft reset if transmit is blocking. Perhaps the latest IDF version is better suited for such use now, well worth checking out?

**Comment by terjeio** [comment]
I've added your uart2 code and a FTDI serial > USB converter with TX > RX connected to `GPIO_NUM_33 `and receiving works when the pin mapping added in` uartConfig()`:

 `uart_set_pin(1, UART_PIN_NO_CHANGE, GPIO_NUM_33, UART_PIN_NO_CHANGE, UART_PIN_NO_CHANGE);`

Your `uart2WriteS()` calls `uartPutC()` should be `uart2PutC()`? Or did you do that intentionally?

**Comment by terjeio** [comment]
[esp32-hal-uart.zip](https://github.com/terjeio/grblHAL/files/4147255/esp32-hal-uart.zip)

Here is an attempt to add the second port without (too much) duplication of code, RX only so requires only one extra pin.

**Comment by terjeio** [comment]
I believe I have cracked it - running some tests now, next up is with telnet streaming. Will upload code here when completed. Not easy to debug - I miss a real debugger...

**Comment by jschoch** [comment]
got an early start on this today before work and my latest commit f879980 seems to work however it starts up listening to input from uart2 and printing status to uart1.  if I toggle the mpg_mode switch a few times it starts behaving.  It seems you can't run uart2Init twice without a panic.  Looking forward to your update.

**Comment by terjeio** [comment]
Here it is, not entirely happy yet but should be good for serial comms. After disconnect from a telnet session it worked for a little while and then just hang... Revenge for me wanting a real debugger?

[ESP32MPG_b.zip](https://github.com/terjeio/grblHAL/files/4150207/ESP32MPG_b.zip)

**Comment by terjeio** [comment]
I forgot this change in `grbl/stream.h`:
```
typedef enum {
    StreamType_Serial = 0,
    StreamType_MPG,
    StreamType_Bluetooth,
    StreamType_Telnet,
    StreamType_WebSocket,
    StreamType_SDCard,
    StreamType_FlashFs,
    StreamType_Redirected,
    StreamType_Null
} stream_type_t;
```

added `StreamType_MPG`.

**Comment by jschoch** [comment]
testing this, wondering about TX, seems you are assuming TX should be off.  I think it should be optional but I was wondering what your logic was for that?  where do msgs go when the MPG is connected?  I dusted off an old setup I had been tinkering with that uses the position to update a DRO screen on a oled.  I guess I can see a few things.

pros of no TX:

1. you don't really need to "ack" commands with the input controls.  you can just spam them assuming you can see the status on the sender or something else.
2. this simplifies the "hardware pendant" event handling a ton but you can't have remote DRO/status display.

cons:

1.  If you want to operate without a head you can't see what your settings are.
2 if you are in alarm I guess you can map something to send reset or $X and pray.
3. you don't get to see what error or alarm state the controller is in so you might make a bad assumption.
4. I assume you can fill the buffer which is bad

I also think it would be nice to have an option to echo reports and or msgs to uart1 while also sending them to uart2 for debugging.

**Comment by jschoch** [comment]
ok, i had my rx pin wrong when i first compiled this so i now see the status updates on uart1 from the input on uart2

**Comment by terjeio** [comment]
Output is always going to the USB connected serial port so no need to duplicate it, just connect to uart1 output on GPIO1. Saves one GPIO pin - ESP32 is a bit short on those.

A plus is, at least with my sender, that the sender will get all status report and thus keep its UI in sync with the MPG (and vice versa). A couple of senders I've tried fall over when getting unsolicited status reports - I regard those as badly implemented and unusable together with a MPG. So for any of those it may be better with a separate TX and silence uart1 completely...

**Comment by jschoch** [comment]
doh, i should have thought of that!

Still testing but it seems to work well so far.  Alpha 4 had some issues but they may be related to something else...  lots of tinkering happening.

**Comment by jschoch** [comment]
when starting the sender with the controller in MPG mode the alpha 4 sender doesn't seem to get out of the wait for MPG mode and has to be killed.  restart and it hung.  finally it re-presented the com selection dialog and it was showing updates from the MPG sender.  Maybe being killed in the first place put it in a bad state.

**Comment by terjeio** [comment]
Alpha 4 has issues for sure, found a couple while testing this. I guess more code should be moved to the grbl viewmodel - work in progress.

I just ordered a secondhand NSK ballscrew for the lathe (for Z-axis - C2 grade),  more to play with. I have [my MPG](https://github.com/terjeio/GRBL_MPG_DRO_BoosterPack) connected to the lathe, I do live testing of the sender on that setup.

**Comment by terjeio** [comment]
Does the sender reset the ESP32 when connecting? If so, that may be one reason. If the sender receives any input on RX on startup it assumes a MPG is in control and it shows the MPG dialog. ESP32 outputs a lot on reset that confuses the sender. I may need to add better parsing and/or delays to get around that. Hard resetting the ESP32 after a reflash may help as a reflash leaves RTS/DTR in a state that triggers reset on connect (at least for me).

Also, the MPG need to issue regular real-time report requests when it is in control for correct operation.

ESP32 is surely not the easiest to work with with all its quirks...

**Comment by jschoch** [comment]
just did a few tests on my lunch break, it was crashing the esp32 but I can't reproduce it now.   I also noticed it timed out or something but when i connected the idf monitor it started working again.  my test setup is .... lacking.  I need to hook up a bigger LCD and cut down on the mass of dupont wires.  I should get this test board hooked up to a motor tonight after work.

**Comment by terjeio** [comment]
Ok - I've looked into the sender code for how to handle a connect reboot of the ESP32, not easy when the MPG is thrown into the picture. The sender needs to know when grbl is ready to be queried for settings etc. so it can configure itself, if a MPG is in control the only way the sender can (currently) detect that is to check if realtime reports are beeing output. Perhaps a new realtime command should be added, always open for all streams whether active or not, returning some status?

Ideally a separate project should be set up for the specification of the grbl interface, properly versioned, and adhered to by all ports/senders - but I guess that is not going to happen.

Anyway a more formalized specification is required for the MPG/grblHAL interaction at boot time - a simple (mechanical) switch is not going to work.

The pull low, switch to input with pullup when ready messaging I use via the mode pin is not going to cut it with the ESP32 due to its extremely long boot time, especially when networking is enabled. Back to the drawing board... perhaps even adding a transistor or two.

**Comment by jschoch** [comment]
it hasn't crashed really.  I did notice it pukes out a bunch of debug type stuff when you write a value in the settings with the sender.

here's a quick video of my 2nd attempt at velocity based jog control.   

https://youtu.be/BDqUbOIiuCg

i wanted to ask if you had considered parsing out the command buffer data.  I didn't see it in your grbl_data struct which i'm also using for my MPG "pendant".  While I don't get buffer full issues with a high feed rate, I did see them with a less steep curve for my feed rates.   I think if i add some exponential average smoothing I may be able to get decent results.

it seems the biggest factors for smoothness is getting the timing of the routines that measure velocity and detect that velocity along with the slope of the curve you use.  I looked at your booster jog code and wasn't exactly sure how it worked with respect to velocity.  Are you using the formula proposed by sonny?  I think I understand it but I couldn't figure out how to apply it.
 
here's some notes I took

/* terjeio's stuff

  // gets a snapshot of the current mpg position
  pos = MPG_GetPosition();

  // get distance between mpg position and the projected move position
  delta_z = (float)(pos->z.position - axis[Z_AXIS].mpg_position) * axis[Z_AXIS].mpg_factor / 400.0f;

  // update mpg_position to snapshot position
  axis[Z_AXIS].mpg_position = pos->z.position;

  // absDistance is a bool, maybe setting absolute mode moves?
  if(grbl_data->absDistance)
    // mpg_base is reset in MPG_ResetPosition when grbl_dat->changed.mpg is true
    axis[Z_AXIS].mpg_base += delta_z;

  // velocity *50 seems to be used to set the feedrate
  velocity = pos->z.velocity;
  sprintf(append(buffer), "Z%.3f", grbl_data->absDistance ? axis[Z_AXIS].mpg_base - grbl_data->offset[Z_AXIS] : delta_z);


  formula:

  dt is estimated jog time
  v current jog rate
  N is the number of planner blocks N=15

  dt > v^2 / (2 * a * (N-1))

  T = dt * N  ; computes latency

  max_jog_rate is rate in mm/s/s

  a is the max acceleration along the jog vector

estimated_jog_time = current_jog_rate / ( 2 * max_jog_rate_accel * (buffer_queue -1))
 // somone posted about a joystick implementation
  estimated_jog_time = current_jog_rate / (2 * max_jog_rate_accel *10)

  jog_distance = current_jog_rate * estimated_jog_time

    */

so do you decrement the step size until you have an acceptable latency?  That seems a bit brutish to me, but my brain hasn't developed another way to apply it other than a precalculated lookup table or something.

**Comment by terjeio** [comment]
Adding more fields to the data struct should be straightforward, I have added whatever I need for my MPG. Note that grblHAL has quite a deep input buffer compared to grbl, 1024 bytes is the default (vs. 128 for grbl).

The formula I use is not for jogging - the MPG wheels generates "normal" G1 commands in order to simulate physical handwheels on the machine - at x1 "gain" 1 turn is 1mm movement. The formula is rather crude for now resulting in jerky movements at low feed rates, partly to do with the sample rate (100ms) and a linear relation between MPG wheel velocity and the feedrate? Some of the jerkiness is also related to the fact that the MPG wheels has detents - it is impossible to move them slowly and smoothly at the same time. The formula I use can surely be improved - I need to put some effort into that at some point. 

A feature in my MPG I often find useful is when turning the MPG wheel the DRO changes to display the target position (in a different colour), I use that to get feedback for when to slow down/stop turning.

My MPG has jog buttons as well, works same as keyboad jogging. A homing button has dual function, a long press to trigger homing and a short press to toggle between jog modes (fast, slow, step).

From your video I took it that you sometimes get a (negative) overshoot when the jog ends. I have changed the jog cancel command in grblHAL to also flush the serial input buffer _and_ the command buffer (in protocol.c), so it should be a lot more robust than the original grbl implementation. Therefore I wonder if you issue a jog cancel after the MPG wheel stops? And perhaps on a direction change as well?

**Comment by jschoch** [comment]
Perhaps a combination of approaches would work well.  My slow jog seems to be working well.  At higher rates it tops out on the step size anyway and only uses the velocity to stop.   The formula I'm using is something like this:

```c
// i average 2 readings and I may want to do more smoothing if I can
// I could also try to do this in the encoder isr.
velocity_calculate interval = 20;  decay to zero between velocity checks.  
velocity_check interval = 20; 

mpg_factor = 0.1;

// make a curve by cubing the axis velocity, this is pretty shallow at the lower velocities
// velocity needs to be > 100 for a move > .01mm.  0.00000015 has 0.01 moves at 50 velocity
float tmpStepSize = (axis.vel * axis.vel * axis.vel) * 0.00000001;

if(tmpStepSize < 2.0){
      stepSize = tmpStepSize;
}else{
      stepSize = 2;
}

// no idea why this is a long
 long velocity(){
      // not sure if this is enough resolution for doing it in the isr
      newtime = millis();
      current_vel = abs(pos - vel_old_pos) * 1000 / (newtime - oldtime);
      // this should be a bit smaller
      if(current_vel > 5){
        vel = (oldvel + current_vel)/2;
        oldvel = vel;
      }else{
        vel = 0;
        oldvel = 0;
      }
...
```

the curve looks like this:

velocity curve

I'm issuing JOG_CANCEL but I don't think that is the problem.  the encoder is so smooth and so high resolution that if you don't pick your finger straight up off the wheel it can stick and cause the encoder wheel to backwards.  I mentioned adding a detent to it to prevent that but I now see your point about the detent making smooth velocity hard (it is already hard).

I like your idea of putting the projected position on the display.  I have a few new color displays I could use, that screen is too small!  

I thought it would be interesting to add functionality to do things like full passes based on some virtual stops.  something like go from current position to virtual stop X and then back, or even add a stepover value in y.  This would be handy on both the mill and the lathe.  I think you could have a toggle that allows you to use the jog wheel to set the jog distance without moving and then execute the move to and back.   Add in realtime feedrate overloads and it might be a time saver.  The small mill i'm converting has all ball screws and I don't think I have an elegant way to lock them for any manual mode.

**Comment by jschoch** [comment]
I had been thinking of using a joystick.  I have a few of these

https://www.seeedstudio.com/Analog-joystick-p-282.html

anyway, it just occurred to me that I can use one axis for feed and one axis for step.  That might be a nice way to jog!

**Comment by ithinkido** [comment]
https://youtu.be/ITgh5epyPRk

**Comment by terjeio** [comment]
Using a joystick would be nice, a good alternative to the buttons I use for my MPG.

Alpha 5 of the sender is just up, should behave better together with ESP32. At least it does so when I disabled all log messages in menuconfig. If the ESP32 get reset on connect the sender will now wait for boot to complete (takes around 5 seconds with WiFi enabled).

**Comment by terjeio** [comment]
@ithinkido FYI I've just run your EASTER.nc.txt file with grblHAL without problems (after fixing some bad bluetooth code). grblHAL does not use any Arduino libraries and I try to keep code at the driver level running in interrupt context if possible, avoiding as much overhead as possible.

**Comment by ithinkido** [comment]
> @ithinkido FYI I've just run your EASTER.nc.txt file with grblHAL without problems (after fixing some bad bluetooth code). grblHAL (for ESP32) does not use any Arduino libraries and I try to keep code at the driver level running in interrupt context if possible, avoiding as much overhead as possible.

I am starting to see bunnies in my sleep. That file has been through my system more than 100 times in test......😂
Hopefully it provides a good test ground, it seems to have the magic ability to break even the most stable of setups !

**Comment by terjeio** [comment]
@ithinkido 

And I've fallen into a deep rabbit hole with this...

A was a bit in quick in claiming grblHAL was good, it failed to respond correctly when outputting the $$ response.  I did not handle congestion at all in the code...

I did some research and ended up with studying what I believe is the [Arduino library](https://github.com/espressif/arduino-esp32/blob/master/libraries/BluetoothSerial/src/BluetoothSerial.cpp
) used by Grbl_ESP32. I decided to try a similar approach to handling transmission but ended up with some instability, research into a solution led me to a [support case](https://www.freertos.org/FreeRTOS_Support_Forum_Archive/November_2017/freertos_Task_hangs_on_xQueueReceive_e37ed619j.html) at freetos.org. Changing my code based on suggestions there seems to have solved my instability problems. From that I am wondering if perhaps the Arduino library has similar issues, this since the same way of coding is used as discussed in the support case.

I am not going to follow up on this myself other than ensuring grblHAL works as intended, it is up to you if you will bring this into the discussion regarding your bunny case.

I will update the repository later when I've done some more testing. It should be noted that it looks like both my implementation and the Arduino library is based on the same Espressif example.

Back to running your bunny through its paces...

**Comment by ithinkido** [comment]
> @ithinkido
> 
> And I've fallen into a deep rabbit hole with this...
> 
I know what you mean
>

**Comment by jschoch** [comment]
closing this

**Pull request closed without merging**
